In [110]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


print(torch.__version__)

2.11.0


### Introduction to Tensors

### Creating tensors

PyTorch tensors are created using: https://docs.pytorch.org/docs/stable/tensors.html

In [111]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [112]:
 scalar.ndim

0

In [113]:
# get tensor back as Python int
scalar.item()

7

In [114]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [115]:
vector.ndim

1

In [116]:
vector.shape

torch.Size([2])

In [117]:
# Matrix
MATRIX = torch.tensor([[7, 8],
                       [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [118]:
MATRIX.ndim

2

In [119]:
MATRIX[1]

tensor([ 9, 10])

In [120]:
MATRIX.shape

torch.Size([2, 2])

In [121]:
# TENSOR
TENSOR = torch.tensor([[[1,2,3],
                       [3,6,9],
                      [2,34,5]]])
TENSOR


tensor([[[ 1,  2,  3],
         [ 3,  6,  9],
         [ 2, 34,  5]]])

In [122]:
TENSOR.ndim

3

In [123]:
TENSOR.shape

torch.Size([1, 3, 3])

In [124]:
TENSOR[0]

tensor([[ 1,  2,  3],
        [ 3,  6,  9],
        [ 2, 34,  5]])

### Random Tensors

## Why random tensors?

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to bettter represent the data.

Start with random numbres -> look at data -> update random numbers -> look at data -> update random numbers

Torch random tensors - https://docs.pytorch.org/docs/stable/generated/torch.rand.html

In [125]:
# Create a random tensor of size (3,4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.8694, 0.5677, 0.7411, 0.4294],
        [0.8854, 0.5739, 0.2666, 0.6274],
        [0.2696, 0.4414, 0.2969, 0.8317]])

In [126]:
random_tensor.ndim

2

In [127]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(3, 224, 224)) # height, width, colour channels (R, G, B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

## Zeros and Ones

In [128]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [129]:
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [130]:
# Create a tensor of all ones
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [131]:
ones.dtype

torch.float32

In [132]:
random_tensor.dtype

torch.float32

### Creating a range of tensors-like

In [133]:
# Use torch.arange() and get deprecated message, use torch.arange()
one_to_ten = torch.arange(start=1, end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [134]:
# Creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes
**Note**: Tensor datatypes is one of the 3 big errors you'll run into with PyTorch & deep learning:
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device.

Precision in computing: 
https://en.wikipedia.org/wiki/Precision_(computer_science)

In [135]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # what datatype is the tensor(e.g. float32 or float16)
                               device=None, # what device your tensor is on
                               requires_grad=False) # whether or not to track gradients with this tensor operations

float_32_tensor

tensor([3., 6., 9.])

In [136]:
float_32_tensor.dtype

torch.float32

In [137]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [138]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [139]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [140]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

### Getting information from tensors (tensor attributes)

1. Tensors not right datatype - to do get datatype from a tensor, can use 'tensor.dtype'
2. Tensors not right shape - to get shape from a tensor, can use 'tensor.shape'
3. Tensors not on the right device - to get device from a tensor, can use 'tensor.device'



In [141]:
# Create a tensor
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.5745, 0.9200, 0.3230, 0.8613],
        [0.0919, 0.3102, 0.9536, 0.6002],
        [0.0351, 0.6826, 0.3743, 0.5220]])

In [142]:
# Find out details about some tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.5745, 0.9200, 0.3230, 0.8613],
        [0.0919, 0.3102, 0.9536, 0.6002],
        [0.0351, 0.6826, 0.3743, 0.5220]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


### Manipulating Tensors (tensor operations)

Tensor operations include:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix Multiplication

In [143]:
# create a tensor and add 10 to it
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [144]:
# Multiply tensor by 10
tensor * 10


tensor([10, 20, 30])

In [145]:
tensor

tensor([1, 2, 3])

In [146]:
# Subtract 10
tensor - 10

tensor([-9, -8, -7])

In [147]:
# Try out PyTorch in-built functions
torch.mul(tensor, 10)


tensor([10, 20, 30])

In [148]:
torch.add(tensor, 10)

tensor([11, 12, 13])

### Matrix Multiplication

Two main ways of performing multiplication in neural networks and deep learning: 

1. Element-wise multiplication
2. Matrix multiplication (dot product)

More information on  multiplying matrices - https://www.mathsisfun.com/algebra/matrix-multiplying.html

There are two main rules that performing matrix multiplication needs to satisfy:
1. The **inner dimesnions** must match:
* `(3, 2) @ (3, 2)` won't work
* `(2, 3) @ (3, 2)` will work
* `(3, 2) @ (2, 3)` will work
2. The resulting matrix has the shape of the **outer dimensions**:
*`(2,3) @ (3,2)` -> `(2,2)`
*`(3,2) @ (2,3)` -> `(3,3)`

In [149]:
torch.matmul(torch.rand(10,10), torch.rand(10, 10)).shape

torch.Size([10, 10])

In [150]:
# Element wise multiplication
print(tensor, "*", tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [151]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [152]:
# Matrix multiplication by hand
1*1  + 2*2 + 3*3

14

In [153]:
%%time 
value = 0
for i in range(len(tensor)):
    value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: user 365 μs, sys: 667 μs, total: 1.03 ms
Wall time: 1.04 ms


In [154]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 47 μs, sys: 14 μs, total: 61 μs
Wall time: 54.8 μs


tensor(14)

### One of the most common errors in deep learning: shape errors


In [155]:
# Shapes for matrix multiplication
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])

tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]])

# torch.mm(tensor_A, tensor_B) # torch.mm is the same as torch.matmul (it's an alias for writing less code)
torch.matmul(tensor_A, tensor_B.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

In [156]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

To fix our tensor hape issues, we can manipulate the shape of one of our tensors using a **transpose**.

A **transpose** switches the axes or dimensions of a given tensor.
    

In [157]:
tensor_B

tensor([[ 7, 10],
        [ 8, 11],
        [ 9, 12]])

In [158]:
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [159]:
# The matrix multiplication operation works when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}")
print(f"New Shapes: tensor_A ={tensor_A.shape} (same sahape as above), tensor_B.T = {tensor_B.T.shape}")
print(f"Multiplying: {tensor_A.shape} @ {tensor_B.T.shape} <- inner dimensions must match")
print("Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f"\nOutput shape: {output.shape}")


Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])
New Shapes: tensor_A =torch.Size([3, 2]) (same sahape as above), tensor_B.T = torch.Size([2, 3])
Multiplying: torch.Size([3, 2]) @ torch.Size([2, 3]) <- inner dimensions must match
Output:

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

Output shape: torch.Size([3, 3])


## Finding the min, max, mean, sum, etc (tensor aggregation)

In [160]:
# Create a tensor
x = torch.arange(1, 100, 10)
x, x.dtype

(tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91]), torch.int64)

In [161]:
# Find the min
torch.min(x), x.min()

(tensor(1), tensor(1))

In [162]:
# Find the max
torch.max(x), x.max()

(tensor(91), tensor(91))

In [163]:
# Find the mean - note; the torch.mean() function requires a tensor of float32 datatype to work
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(46.), tensor(46.))

In [164]:
# Find the sum
torch.sum(x), x.sum()

(tensor(460), tensor(460))

# Finding the positional min and max

In [165]:
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [166]:
# Find the position in tensor that has the minimum value with argmin() -> returns index position of target tensor where the minimum value occurs
x.argmin()

tensor(0)

In [167]:
x[0]

tensor(1)

In [168]:
# Find the position in tensor that has the maximum value with argmax() -> returns index position of target tensor where the maximum value occurs
x.argmax()

tensor(9)

## Reshaping, stacking, squeezing and unsqueezing tensors

* Reshaping - reshapes an input tensor to a defined shape
* View - Return a view of an input tensor of a certain shape but keep the same memory as the original tensor.
* Stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeeze - removes all '1' dimensions from a tensor
* Unsqueeze - add a '1' dimension to a target tensor
* Permute - Return a view of the input with dimensions permuted (swapped) in a certain way.

In [169]:
# Let's create a tensor
import torch
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [170]:
# Add an extra dimensiom
x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [171]:
# Change the view
z = x.view(1, 9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [172]:
 # Changing z changes x (because a view of a tensor shares the same memory as the original input)
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [173]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [174]:
# torch.squeeze() - removes all single dimensions from a tensor
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# Remove extra dimensions from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous shape: torch.Size([1, 9])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape: torch.Size([9])


In [175]:
# torch.unsqueeze() - adds a single dimensions to a target tensor at a specific dim (dimension)
print(f"Previous target: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

# Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous target: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])

New tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
New shape: torch.Size([1, 9])


In [176]:
# torch.permute - rearranges the dimensions of a target tensor in a specified order
x_original = torch.rand(size=(224, 224, 3)) # [height, width, colour_channels]

# Permute the original tensor to rearrange the axis (or dim) order
x_permuted = x_original.permute(2, 0, 1) # shifts axis o->1, 1->2, 2->0

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}") # [colour_channels, height, width]

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


In [177]:
x_original[0, 0, 0] = 71818 
x_original[0, 0, 0], x_permuted[0, 0, 0]

(tensor(71818.), tensor(71818.))

## Indexing (selecting data from tensors)

Indexing with PyTorch is similar to indexing with NumPy

In [178]:
# Creating a tensor
import torch
x = torch.arange(1,10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [179]:
# Let's index on our new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [180]:
# Let's index on the middle bracket (dim=1)
x[0, 0]

tensor([1, 2, 3])

In [181]:
# Let's index on the most inner bracket (last dimension)
x[0][2][2]

tensor(9)

In [182]:
# You can also use ":" select "all" of a target dimension
x[:, 0]

tensor([[1, 2, 3]])

In [183]:
# Get all values of 0th and 1st demensions but only index 1 of 2nd dimesion
x[:,:,1]

tensor([[2, 5, 8]])

In [184]:
# Get all values of the 0th dimension but only the 1 index value of 1st and 2nd dimension
x[:, 1, 1]

tensor([5])

In [185]:
# Get index 0 of 0th and 1st dimension and all values of 2nd dimensiom
x[0,0,:]

tensor([1, 2, 3])

In [186]:
# Index on x to return 9
x[0][2][2]

# Index on x to return 3, 6, 9
x[:, :, 2]

tensor([[3, 6, 9]])

## PyTorch tensors and NumPy

NumPy is a popular scientific Python numerical computing library.

And because of this, Pytorch has functionality to interact with it.

* Data in NumPy, want in PyTorch tenso -> `torch,from_numpy(ndarray)`
* PyTorch tensor -> NumPy -> `torch.Tensor.numpy()`

In [187]:
# NumPy array to tensor
import torch
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array) # warning: when converting from numpy -> pytorch, pytorch reflects numpy's default datatype of float64 unless specified otherwise
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [188]:
# Change the value of the array, what will this do to 'tensor'?
array = array + 1 
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [189]:
# Tensor to NumPy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [190]:
# Change the tensor, what happens to `numpy_tensor`?
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducibility (trying to take random out of random)

In short, how a neural network learns:

`start with random numbers -> tensor operations -> update random numbers to try and make them better representations of the data -> again -> again -> again...`

To reduce the randomness in neural networks and PyTorch comes the concept of a **random seed**.
Essentially what the random seed does is "flavour" the randomness.

In [191]:
import torch

# Create two random tensors
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.3670, 0.1667, 0.7490, 0.3919],
        [0.9136, 0.5384, 0.8029, 0.6793],
        [0.2663, 0.5063, 0.0150, 0.9528]])
tensor([[0.6405, 0.7250, 0.6003, 0.6683],
        [0.1815, 0.6204, 0.8131, 0.0921],
        [0.3190, 0.9570, 0.8931, 0.0411]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [192]:
# Lets's make some random but reproducible tensors
import torch

# Set the random seed
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3, 4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


Extra resources for reproducibility:
* https://docs.pytorch.org/docs/stable/notes/randomness.html
* https://en.wikipedia.org/wiki/Random_seed

## Running tensors and PyTroch ojects on the GPUs (and making faster computations)

GPUs  = faster computations on numbers, thanks to CUDA + NVIDIA hardware + PyTorch working behind the scenes.

### 1. Getting a GPU

1. Easiest - Use Google Colab (options to upgrade as well)
2. Use your own GPU
3. Use cloud computing - GCP, AWS, Azure.

For 2, 3 Pytorch + GPU drivers (CUDA) takes a little bit of setting up, to do this refer to PyTorch documentation : http://pytorch.org/get-started/locally/.

### 2. Check for GPU acess with PyTorch.

In [197]:
# Check for GPU acess with PyTorch.
import torch
#torch.cuda.is_available()
print(torch.backends.mps.is_available()) # for mac

True


In [199]:
# Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cpu'

For PyTorch since it's capaable of running compute on the GPU or CPU, it's best practice to setup device agnostic code:    https://docs.pytorch.org/docs/stable/notes/cuda.html

e.g. run on GPU if available, else default to CPU

In [202]:
device = "mps" if torch.mps.is_available() else "cpu"
device

'mps'

In [206]:
# Count number of devices
#torch.cuda.device_count()
#torch


## 3. Putting tensors (and models) on the GPU

The reason we want our tensors/models on the GPU is because using a GPU results in faster computations.

In [209]:
# Create a tensor (default on the CPU)

tensor = torch.tensor([1, 2, 3])
# Tensor not on GPU
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [211]:
# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='mps:0')

### 4. Moving tensors back to the CPU

In [214]:
# If tensor is on GPU, can't trasform it to NumPy
tensor_on_gpu.numpy()

TypeError: can't convert mps:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [216]:
# To fix the GPU tensor with NumPy issue, we can first set it to the CPU
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

In [217]:
tensor_on_gpu

tensor([1, 2, 3], device='mps:0')

## Exercises and Extra-curriculum
See exercises for this notebook here: 
* https://www.learnpytorch.io/00_pytorch_fundamentals/#exercises
* https://github.com/mrdbourke/pytorch-deep-learning/blob/main/extras/exercises/00_pytorch_fundamentals_exercises.ipynb # better on google colab-github option